### PR TITLE
Add Fluent Configuration

### PR DESCRIPTION
**Pull request by gary-lg**
Adds support for fluent code-first configuration. Whilst this simplifies code-
first setup (no need to create an instance of the configuration options class)
it also opens the library up to configuration via appSettings.json or web.config
without needing to make code changes.

### CODE REVIEW

**Comment by thoean** [comment]
Published at https://www.nuget.org/packages/Serilog.Sinks.AwsCloudWatch/4.0.159

**Comment by wparad** [comment]
I don't think we should have done this, the library already support appsettings, and this added unnecessary and bad duplication of the options class.

**Comment by gary-lg** [comment]
@wparad - My understanding is that this commit is what allows configuration via appsettings. App settings translates directly into method calls as you can see in [this post by NBlumhardt](https://nblumhardt.com/2016/03/reading-logger-configuration-from-appsettings-json/) from 2016 . Also  where is the duplication? Are you referring to instantiating the options classes in the fluent static methods?

**Comment by wparad** [comment]
> Are you referring to instantiating the options classes in the fluent static methods?

Yes

> My understanding is that this commit is what allows configuration via appsettings. 

This was already possible.

**Pull request merged**
