### PR TITLE
Add built-in json renderer to format log event into json

### PR DESCRIPTION
**Pull request by hzhengran**
#37

### CODE REVIEW

**Comment by wparad** [comment]
@hzhengran, the library offers a way to pass in custom `logEventRenderers`, see example from #27.  As it is right now the current solution wouldn't be scalable, every time a new renderer would need to be added it would have to be hard coded into the library.  To avoid this the `CloudWatchSinkOptions` takes an `ILogEventRenderer` (see [here](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/master/src/Serilog.Sinks.AwsCloudWatch/CloudWatchSinkOptions.cs#L57).

Additionally adding more extension methods is also something we want to avoid.  A lot of thought has been put into the current set to enable a wide variety of possible implementations while ensuring simplicity.

Given these two points, I am opting to close this PR, but if I missed something please let us know.

**Comment by hzhengran** [comment]
Updated #37.

I agree with your 3rd comments which is adding dependency to `Newtonsoft.Json`. But the default renderer is losing information when rendering an `exception`. 
```
...
Log.Fatal(exception, messageTemplate);
...
```
And adding a Json serializer solves this issue.

The reason why i cannot pass an `ILogEventRenderer` is that i have to initiate the sink via AppConfig which doesn't accept an object value. So I'm adding an extension method that accept string value.

**Comment by wparad** [comment]
> The reason why i cannot pass an ILogEventRenderer is that i have to initiate the sink via AppConfig which doesn't accept an object value. So I'm adding an extension method that accept string value.

Please solve that problem via improving the AppConfig rather than putting the extension here.  I think a lot of people would be benefit from that functionality rather than an extension method here which can only help solve this one use case.

**Comment by thoean** [comment]
An alternative way could be to provide a dedicated library, like a serilog-sinks-awscloudwatch-json-renderer or serilog-sinks-awscloudwatch-xml-renderer etc. and pull in the respective dependencies?

**Pull request closed without merging**
