### PR TITLE
Update AWS SDK CloudWatchLogs version >=3.7.106

### PR DESCRIPTION
**Pull request by williamhowf**
some dependencies for AWS SDK Core has minimum version 3.7.106

### CODE REVIEW

**Comment by wparad** [comment]
Why?

**Comment by williamhowf** [comment]
reason my project is using AWS SDK S3 library and it has dependencies to AWS SDK Core minimum version 3.7
serilog cloud watch log reference AWS SDK Core >= 3.5 and < 3.6
both reference Core library are different version.

**Comment by wparad** [comment]
> reason my project is using AWS SDK S3 library and it has dependencies to AWS SDK Core minimum version 3.7 serilog cloud watch log reference AWS SDK Core >= 3.5 and < 3.6 both reference Core library are different version.

That's just not true, any version of the AWS Core, can be used with this library. Which version did you specify exactly in your project? And why did you pick 3.7.106, is that really the best version this library should depend on?

**Comment by williamhowf** [comment]
workaround, install higher version AWSSDK.Core(i.e: 3.7.204.15) into the project so that current version serilog cloudwatch can install AWSSDK.CloudWatchLogs 3.5.0.9 together.

**Pull request closed without merging**
