### PR TITLE
Adding InstanceIdLogStreamNameProvider to use the machine instance id

### PR DESCRIPTION
**Pull request by kevbite**
Adding InstanceIdLogStreamNameProvider to use the machine instance id as the stream name.

Connects #59

### CODE REVIEW

**Comment by wparad** [comment]
Is there a reason why setting the `logStreamNamePrefix` be the value `Amazon.Util.EC2InstanceMetadata.InstanceId` doesn't work for you?

There are also additional problems that would be solved with the already existing
`LogStreamNameProvider = new ConstantLogStreamNameProvider(Amazon.Util.EC2InstanceMetadata.InstanceId);`
 such as reuse and extensibility.  I hesitant to add custom implementations here, unless there is a good reason.

**Comment by kevbite** [comment]
The `ConstantLogStreamNameProvider` still doesn't match the defaults for a lot of the EC2 configuration, as the `ConstantLogStreamNameProvider` appends a random GUID to the end. So it would be
```
i-0ee992212549ce0e7_97ff70ed-96d1-452d-a125-708a26b9f914
```

Just basing this on the AWS example - https://s3.amazonaws.com/ec2-downloads-windows/CloudWatchConfig/AWS.EC2.Windows.CloudWatch.json
```json
            {
                "Id": "CloudWatchLogs",
                "FullName": "AWS.EC2.Windows.CloudWatch.CloudWatchLogsOutput,AWS.EC2.Windows.CloudWatch",
                "Parameters": {
                    "AccessKey": "",
                    "SecretKey": "",
                    "Region": "us-east-1",
                    "LogGroup": "Default-Log-Group",
                    "LogStream": "{instance_id}"
                }
            },
```

Totally understand that you want to give the ability for customization but don't want to have everyone's implementations but I felt like this one sat well inside the actual package as it's both related to AWS and has no extra external dependencies.

**Comment by wparad** [comment]
There is a reason it appends a guid to the end, what happens when you have multiple containers or processes running on the same machine.  They all can't write to the same stream at the same time, or else they would continue to run into each other (check the SDK documentation).  The solutions provided by this library need to work, and with this suggestion we would be providing a solution which has a problem for everyone who is putting more than one service on a EC2 machine (mostly the default at this point, with Docker, EC2, EKS, etc...)

If you can figure out way to ensure that multiple services won't run into each other on the same machine, we can figure out how to include the implementation.  My additional concern is adding unnecessary classes to this library which don't benefit at least 20% of the population of users.  We would be unnecessarily adding bloat to this library for only a small percentage of users.  We can create another library which just wraps the InstanceId resolution, but that seems like overkill.

**Comment by kevbite** [comment]
Good point about the multiple running on one machine, as we only have 1 to 1 mapping between machine and a log stream within a log group.

**Comment by kevbite** [comment]
Creating another library does seem like overkill. - So I'll just close this and keep it private ;-)

**Pull request closed without merging**
